### ISSUE TITLE
Several Errors when installing

### ISSUE THREAD

**Issue by mem1984** [rohanJa/onlineAuction#7]
Issue 1:
when running:     pip install -r requirements.txt
error is: 
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 2))

Issue 2:
when running:      python manage.py makemigrations
error is:
Traceback (most recent call last):
  File "/Users/nobility/DevProjects/auction/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nobility/DevProjects/auction/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/nobility/DevProjects/auction/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/nobility/DevProjects/auction/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nobility/DevProjects/auction/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/nobility/DevProjects/auction/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/nobility/DevProjects/auction/aahome1/models.py", line 13, in <module>
    from aform.models import Seller, Buyer, User
  File "/Users/nobility/DevProjects/auction/aform/models.py", line 25, in <module>
    class Seller(models.Model):
  File "/Users/nobility/DevProjects/auction/aform/models.py", line 26, in Seller
    user = models.OneToOneField(User)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by FrankCastle84** [comment]
using pycharm, i needed to update the requirements document to solve the issues... new requirements document looks like this:

Django==1.11.29
pytz==2019.2

**Comment by mem1984** [comment]
using pycharm, i needed to update the requirements document to solve the issues... new requirements document looks like this:

Django==1.11.29
pytz==2019.2

**Comment by rohanJa** [comment]
thanks i 
can you create a pull request so that i can merege @FrankCastle84
